create table "public"."event_history" (
    "id" bigint generated by default as identity not null,
    "table_name" text,
    "field_name" text,
    "updated_by" uuid,
    "updated_at" timestamp with time zone default now(),
    "ref_id" text,
    "new_value" text
);


alter table "public"."event_history" enable row level security;

CREATE UNIQUE INDEX event_history_pkey ON public.event_history USING btree (id);

alter table "public"."event_history" add constraint "event_history_pkey" PRIMARY KEY using index "event_history_pkey";

alter table "public"."event_history" add constraint "public_event_history_updated_by_fkey" FOREIGN KEY (updated_by) REFERENCES auth.users(id) not valid;

alter table "public"."event_history" validate constraint "public_event_history_updated_by_fkey";

grant delete on table "public"."event_history" to "anon";

grant insert on table "public"."event_history" to "anon";

grant references on table "public"."event_history" to "anon";

grant select on table "public"."event_history" to "anon";

grant trigger on table "public"."event_history" to "anon";

grant truncate on table "public"."event_history" to "anon";

grant update on table "public"."event_history" to "anon";

grant delete on table "public"."event_history" to "authenticated";

grant insert on table "public"."event_history" to "authenticated";

grant references on table "public"."event_history" to "authenticated";

grant select on table "public"."event_history" to "authenticated";

grant trigger on table "public"."event_history" to "authenticated";

grant truncate on table "public"."event_history" to "authenticated";

grant update on table "public"."event_history" to "authenticated";

grant delete on table "public"."event_history" to "service_role";

grant insert on table "public"."event_history" to "service_role";

grant references on table "public"."event_history" to "service_role";

grant select on table "public"."event_history" to "service_role";

grant trigger on table "public"."event_history" to "service_role";

grant truncate on table "public"."event_history" to "service_role";

grant update on table "public"."event_history" to "service_role";

create policy "select_authenticated_only"
on "public"."event_history"
as permissive
for select
to public
using ((auth.uid() IS NOT NULL));



