create table "public"."companies" (
    "created_at" timestamp with time zone not null default now(),
    "company_name" text,
    "company_domain" text,
    "id" uuid not null default gen_random_uuid()
);


alter table "public"."companies" enable row level security;

create table "public"."eeu_data" (
    "id" integer generated by default as identity not null,
    "report_type" text,
    "use_type_total_area" text,
    "area_units" text,
    "energy_units" text,
    "Heating_Electricity" text,
    "Heating_NaturalGas" text,
    "Heating_DistrictHeating" text,
    "Heating_Other" text,
    "Cooling_Electricity" text,
    "Cooling_DistrictHeating" text,
    "Cooling_Other" text,
    "DHW_Electricity" text,
    "DHW_NaturalGas" text,
    "DHW_DistrictHeating" text,
    "DHW_Other" text,
    "Interior Lighting_Electricity" text,
    "Exterior Lighting_Electricity" text,
    "Plug Loads_Electricity" text,
    "Fans_Electricity" text,
    "Pumps_Electricity" text,
    "Pumps_NaturalGas" text,
    "Process Refrigeration_Electricity" text,
    "ExteriorUsage_Electricity" text,
    "ExteriorUsage_NaturalGas" text,
    "OtherEndUse_Electricity" text,
    "OtherEndUse_NaturalGas" text,
    "OtherEndUse_Other" text,
    "Heat Rejection_Electricity" text,
    "Humidification_Electricity" text,
    "HeatRecovery_Electricity" text,
    "HeatRecovery_Other" text,
    "SolarDHW_On-SiteRenewables" text,
    "SolarPV_On-SiteRenewables" text,
    "Wind_On-SiteRenewables" text,
    "Other_On-SiteRenewables" text,
    "total_Electricity" text,
    "total_NaturalGas" text,
    "total_DistrictHeating" text,
    "total_Other" text,
    "total_On-SiteRenewables" text,
    "total_energy" text,
    "project_name" text,
    "weather_string" text,
    "weather_station" text,
    "climate_zone" text,
    "file_url" text,
    "upload_id" bigint,
    "baseline_design" text,
    "created_at" timestamp with time zone default CURRENT_TIMESTAMP,
    "updated_at" timestamp with time zone default CURRENT_TIMESTAMP,
    "upload_warnings" text,
    "upload_errors" text
);


alter table "public"."eeu_data" enable row level security;

create table "public"."enum_climate_zones" (
    "id" integer generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "name" text,
    "order" smallint,
    "description" text
);


alter table "public"."enum_climate_zones" enable row level security;

create table "public"."enum_energy_codes" (
    "id" integer generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "name" text,
    "order" smallint
);


alter table "public"."enum_energy_codes" enable row level security;

create table "public"."enum_project_construction_categories" (
    "id" integer generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "name" text,
    "order" smallint
);


alter table "public"."enum_project_construction_categories" enable row level security;

create table "public"."enum_project_phases" (
    "id" integer generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "name" text,
    "order" smallint
);


alter table "public"."enum_project_phases" enable row level security;

create table "public"."enum_project_use_types" (
    "id" integer generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "name" text,
    "order" smallint
);


alter table "public"."enum_project_use_types" enable row level security;

create table "public"."enum_report_types" (
    "id" integer generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "name" text,
    "order" smallint
);


alter table "public"."enum_report_types" enable row level security;

create table "public"."enum_upload_statuses" (
    "id" integer generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "name" text,
    "order" smallint
);


alter table "public"."enum_upload_statuses" enable row level security;

create table "public"."profiles" (
    "id" uuid not null,
    "first_name" text,
    "last_name" text,
    "email" text,
    "company_id" uuid,
    "confirmed_at" timestamp with time zone,
    "last_sign_in_at" timestamp with time zone,
    "role" text
);


alter table "public"."profiles" enable row level security;

create table "public"."projects" (
    "created_at" timestamp with time zone not null default now(),
    "project_name" text,
    "climate_zone_id" integer,
    "conditioned_area_sf" real,
    "project_construction_category_id" bigint,
    "project_use_type_id" bigint,
    "company_id" uuid,
    "id" uuid not null default gen_random_uuid()
);


alter table "public"."projects" enable row level security;

create table "public"."uploads" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "area" real,
    "climate_zone_id" bigint,
    "climate_zone_str" text,
    "user_id" bigint,
    "area_units" text,
    "project_phase_id" bigint,
    "design_baseline_type" text,
    "report_type_id" bigint,
    "upload_status_id" integer,
    "energy_code_id" integer,
    "project_construction_category_id" integer,
    "project_id" uuid,
    "project_use_type_id" integer,
    "company_id" uuid,
    "id_uuid" uuid,
    "other_energy_code" text,
    "year" smallint
);


alter table "public"."uploads" enable row level security;

create table "public"."users" (
    "id" integer generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "user_first" text,
    "user_last" text,
    "user_email" text,
    "company_id" uuid
);


alter table "public"."users" enable row level security;

CREATE UNIQUE INDEX climate_zones_pkey ON public.enum_climate_zones USING btree (id);

CREATE UNIQUE INDEX companies_id_uuid_key ON public.companies USING btree (id);

CREATE UNIQUE INDEX companies_pkey ON public.companies USING btree (id);

CREATE UNIQUE INDEX eeu_data_id_key ON public.eeu_data USING btree (id);

CREATE UNIQUE INDEX eeu_data_pkey ON public.eeu_data USING btree (id);

CREATE UNIQUE INDEX energy_codes_pkey ON public.enum_energy_codes USING btree (id);

CREATE UNIQUE INDEX profiles_pkey ON public.profiles USING btree (id);

CREATE UNIQUE INDEX project_construction_categories_id_key ON public.enum_project_construction_categories USING btree (id);

CREATE UNIQUE INDEX project_construction_categories_pkey ON public.enum_project_construction_categories USING btree (id);

CREATE UNIQUE INDEX project_phases_pkey ON public.enum_project_phases USING btree (id);

CREATE UNIQUE INDEX project_use_types_pkey ON public.enum_project_use_types USING btree (id);

CREATE UNIQUE INDEX projects_pkey ON public.uploads USING btree (id);

CREATE UNIQUE INDEX projects_pkey1 ON public.projects USING btree (id);

CREATE UNIQUE INDEX report_types_pkey ON public.enum_report_types USING btree (id);

CREATE UNIQUE INDEX upload_statuses_pkey ON public.enum_upload_statuses USING btree (id);

CREATE UNIQUE INDEX uploads_id_uuid_key ON public.uploads USING btree (id_uuid);

CREATE UNIQUE INDEX users_pkey ON public.users USING btree (id);

alter table "public"."companies" add constraint "companies_pkey" PRIMARY KEY using index "companies_pkey";

alter table "public"."eeu_data" add constraint "eeu_data_pkey" PRIMARY KEY using index "eeu_data_pkey";

alter table "public"."enum_climate_zones" add constraint "climate_zones_pkey" PRIMARY KEY using index "climate_zones_pkey";

alter table "public"."enum_energy_codes" add constraint "energy_codes_pkey" PRIMARY KEY using index "energy_codes_pkey";

alter table "public"."enum_project_construction_categories" add constraint "project_construction_categories_pkey" PRIMARY KEY using index "project_construction_categories_pkey";

alter table "public"."enum_project_phases" add constraint "project_phases_pkey" PRIMARY KEY using index "project_phases_pkey";

alter table "public"."enum_project_use_types" add constraint "project_use_types_pkey" PRIMARY KEY using index "project_use_types_pkey";

alter table "public"."enum_report_types" add constraint "report_types_pkey" PRIMARY KEY using index "report_types_pkey";

alter table "public"."enum_upload_statuses" add constraint "upload_statuses_pkey" PRIMARY KEY using index "upload_statuses_pkey";

alter table "public"."profiles" add constraint "profiles_pkey" PRIMARY KEY using index "profiles_pkey";

alter table "public"."projects" add constraint "projects_pkey1" PRIMARY KEY using index "projects_pkey1";

alter table "public"."uploads" add constraint "projects_pkey" PRIMARY KEY using index "projects_pkey";

alter table "public"."users" add constraint "users_pkey" PRIMARY KEY using index "users_pkey";

alter table "public"."companies" add constraint "companies_id_uuid_key" UNIQUE using index "companies_id_uuid_key";

alter table "public"."eeu_data" add constraint "eeu_data_id_key" UNIQUE using index "eeu_data_id_key";

alter table "public"."eeu_data" add constraint "public_eeu_data_upload_id_fkey" FOREIGN KEY (upload_id) REFERENCES uploads(id) not valid;

alter table "public"."eeu_data" validate constraint "public_eeu_data_upload_id_fkey";

alter table "public"."enum_project_construction_categories" add constraint "project_construction_categories_id_key" UNIQUE using index "project_construction_categories_id_key";

alter table "public"."profiles" add constraint "profiles_id_fkey" FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE not valid;

alter table "public"."profiles" validate constraint "profiles_id_fkey";

alter table "public"."profiles" add constraint "public_profiles_company_id_fkey" FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE SET NULL not valid;

alter table "public"."profiles" validate constraint "public_profiles_company_id_fkey";

alter table "public"."projects" add constraint "projects_climate_zone_id_fkey" FOREIGN KEY (climate_zone_id) REFERENCES enum_climate_zones(id) not valid;

alter table "public"."projects" validate constraint "projects_climate_zone_id_fkey";

alter table "public"."projects" add constraint "projects_company_id_fkey" FOREIGN KEY (company_id) REFERENCES companies(id) not valid;

alter table "public"."projects" validate constraint "projects_company_id_fkey";

alter table "public"."projects" add constraint "projects_project_construction_category_id_fkey" FOREIGN KEY (project_construction_category_id) REFERENCES enum_project_construction_categories(id) not valid;

alter table "public"."projects" validate constraint "projects_project_construction_category_id_fkey";

alter table "public"."projects" add constraint "projects_project_use_type_id_fkey" FOREIGN KEY (project_use_type_id) REFERENCES enum_project_use_types(id) not valid;

alter table "public"."projects" validate constraint "projects_project_use_type_id_fkey";

alter table "public"."uploads" add constraint "public_uploads_climate_zone_id_fkey" FOREIGN KEY (climate_zone_id) REFERENCES enum_climate_zones(id) ON DELETE SET NULL not valid;

alter table "public"."uploads" validate constraint "public_uploads_climate_zone_id_fkey";

alter table "public"."uploads" add constraint "public_uploads_energy_code_id_fkey" FOREIGN KEY (energy_code_id) REFERENCES enum_energy_codes(id) ON DELETE SET NULL not valid;

alter table "public"."uploads" validate constraint "public_uploads_energy_code_id_fkey";

alter table "public"."uploads" add constraint "public_uploads_project_construction_category_id_fkey" FOREIGN KEY (project_construction_category_id) REFERENCES enum_project_construction_categories(id) ON DELETE SET NULL not valid;

alter table "public"."uploads" validate constraint "public_uploads_project_construction_category_id_fkey";

alter table "public"."uploads" add constraint "public_uploads_project_id_fkey" FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE SET NULL not valid;

alter table "public"."uploads" validate constraint "public_uploads_project_id_fkey";

alter table "public"."uploads" add constraint "public_uploads_project_phase_id_fkey" FOREIGN KEY (project_phase_id) REFERENCES enum_project_phases(id) ON DELETE SET NULL not valid;

alter table "public"."uploads" validate constraint "public_uploads_project_phase_id_fkey";

alter table "public"."uploads" add constraint "public_uploads_project_use_type_id_fkey" FOREIGN KEY (project_use_type_id) REFERENCES enum_project_use_types(id) ON DELETE SET NULL not valid;

alter table "public"."uploads" validate constraint "public_uploads_project_use_type_id_fkey";

alter table "public"."uploads" add constraint "uploads_company_id_fkey" FOREIGN KEY (company_id) REFERENCES companies(id) not valid;

alter table "public"."uploads" validate constraint "uploads_company_id_fkey";

alter table "public"."uploads" add constraint "uploads_id_uuid_key" UNIQUE using index "uploads_id_uuid_key";

alter table "public"."uploads" add constraint "uploads_report_type_id_fkey" FOREIGN KEY (report_type_id) REFERENCES enum_report_types(id) not valid;

alter table "public"."uploads" validate constraint "uploads_report_type_id_fkey";

alter table "public"."uploads" add constraint "uploads_upload_status_id_fkey" FOREIGN KEY (upload_status_id) REFERENCES enum_upload_statuses(id) not valid;

alter table "public"."uploads" validate constraint "uploads_upload_status_id_fkey";

alter table "public"."uploads" add constraint "uploads_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE RESTRICT not valid;

alter table "public"."uploads" validate constraint "uploads_user_id_fkey";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.custom_access_token_hook(event jsonb)
 RETURNS jsonb
 LANGUAGE plpgsql
AS $function$
  declare
    claims jsonb;
    company_id uuid; -- Assuming company_id is of type UUID
  begin
    -- Fetch the company_id for the user from the profiles table
    select company_id into company_id from profiles where user_id = event->>'user_id'::uuid;

    -- Proceed only if a company_id was found
    if company_id is not null then
      claims := event->'claims';

      -- Check if 'app_metadata' exists in claims
      if jsonb_typeof(claims->'app_metadata') is null then
        -- If 'app_metadata' does not exist, create an empty object
        claims := jsonb_set(claims, '{app_metadata}', '{}');
      end if;

      -- Insert the company_id into the claims
      -- Assuming you want to add the company_id under app_metadata
      claims := jsonb_set(claims, '{app_metadata,company_id}', to_jsonb(company_id::text));

      -- Update the 'claims' object in the original event
      event := jsonb_set(event, '{claims}', claims);
    end if;

    -- Return the modified or original event
    return event;
  end;
$function$
;

CREATE OR REPLACE FUNCTION public.handle_new_user()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
begin
  insert into public.profiles (id, email, company_id)
  values (new.id, new.email, (new.raw_user_meta_data->>'company_id')::uuid);
  return new;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.handle_user_update()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
    UPDATE public.profiles
    SET email = NEW.email, -- Update fields as necessary
        updated_at = CURRENT_TIMESTAMP, -- Assume you've added an updated_at column
        confirmed_at = NEW.confirmed_at
    WHERE id = NEW.id;
    RETURN NEW;
END;
$function$
;

create or replace view "public"."latest_project_uploads5" as  SELECT p.project_name,
    ert.name AS report_type,
    eec.name AS energy_code,
    p.company_id,
    p.id
   FROM (((projects p
     JOIN uploads u ON ((p.id = u.project_id)))
     JOIN enum_energy_codes eec ON ((u.energy_code_id = eec.id)))
     JOIN enum_report_types ert ON ((u.report_type_id = ert.id)))
  WHERE (u.created_at = ( SELECT max(u2.created_at) AS max
           FROM uploads u2
          WHERE (u2.project_id = p.id)));


create or replace view "public"."project_energy_summary4" as  WITH ranked_uploads AS (
         SELECT p.id AS project_id,
            p.project_name,
            ud.report_type,
            ((cz.name || ' - '::text) || cz.description) AS climate_zone,
            ud.total_energy,
            ut.name AS project_use_type,
            ud.baseline_design,
                CASE
                    WHEN (u.year IS NOT NULL) THEN ((u.year || ' - '::text) || pp.name)
                    ELSE pp.name
                END AS project_phase,
            ud.use_type_total_area AS conditioned_area,
            row_number() OVER (PARTITION BY p.id, ud.baseline_design ORDER BY u.created_at DESC) AS rn,
            p.company_id,
                CASE
                    WHEN (((regexp_replace(ud."SolarDHW_On-SiteRenewables", '\D'::text, ''::text, 'g'::text) <> ''::text) AND ((regexp_replace(ud."SolarDHW_On-SiteRenewables", '\D'::text, ''::text, 'g'::text))::numeric > (0)::numeric)) OR ((regexp_replace(ud."SolarPV_On-SiteRenewables", '\D'::text, ''::text, 'g'::text) <> ''::text) AND ((regexp_replace(ud."SolarPV_On-SiteRenewables", '\D'::text, ''::text, 'g'::text))::numeric > (0)::numeric)) OR ((regexp_replace(ud."Other_On-SiteRenewables", '\D'::text, ''::text, 'g'::text) <> ''::text) AND ((regexp_replace(ud."Other_On-SiteRenewables", '\D'::text, ''::text, 'g'::text))::numeric > (0)::numeric))) THEN 'Yes'::text
                    ELSE 'No'::text
                END AS renewables
           FROM (((((projects p
             JOIN uploads u ON ((p.id = u.project_id)))
             JOIN eeu_data ud ON ((u.id = ud.upload_id)))
             LEFT JOIN enum_project_phases pp ON ((u.project_phase_id = pp.id)))
             LEFT JOIN enum_project_use_types ut ON ((u.project_use_type_id = ut.id)))
             LEFT JOIN enum_climate_zones cz ON ((ud.climate_zone = cz.name)))
        ), baseline AS (
         SELECT ranked_uploads.project_id,
            ranked_uploads.project_name,
            ranked_uploads.report_type,
            ranked_uploads.climate_zone,
            ranked_uploads.project_phase,
            ranked_uploads.total_energy,
                CASE
                    WHEN ((ranked_uploads.conditioned_area)::numeric > (0)::numeric) THEN (((ranked_uploads.total_energy)::numeric / (ranked_uploads.conditioned_area)::numeric) * (1000)::numeric)
                    ELSE NULL::numeric
                END AS total_energy_per_unit_area_baseline,
            ranked_uploads.baseline_design,
            ranked_uploads.conditioned_area,
            ranked_uploads.rn,
            ranked_uploads.company_id,
            ranked_uploads.project_use_type,
            ranked_uploads.renewables
           FROM ranked_uploads
          WHERE ((ranked_uploads.baseline_design = 'baseline'::text) AND (ranked_uploads.rn = 1))
        ), design AS (
         SELECT ranked_uploads.project_id,
            ranked_uploads.project_name,
            ranked_uploads.report_type,
            ranked_uploads.climate_zone,
            ranked_uploads.project_phase,
            ranked_uploads.total_energy,
                CASE
                    WHEN ((ranked_uploads.conditioned_area)::numeric > (0)::numeric) THEN (((ranked_uploads.total_energy)::numeric / (ranked_uploads.conditioned_area)::numeric) * (1000)::numeric)
                    ELSE NULL::numeric
                END AS total_energy_per_unit_area_design,
            ranked_uploads.baseline_design,
            ranked_uploads.conditioned_area,
            ranked_uploads.rn,
            ranked_uploads.company_id,
            ranked_uploads.project_use_type,
            ranked_uploads.renewables
           FROM ranked_uploads
          WHERE ((ranked_uploads.baseline_design = 'design'::text) AND (ranked_uploads.rn = 1))
        )
 SELECT COALESCE(b.project_id, d.project_id) AS project_id,
    COALESCE(b.project_name, d.project_name) AS project_name,
    COALESCE(b.report_type, d.report_type) AS report_type,
    COALESCE(b.climate_zone, d.climate_zone) AS climate_zone,
    b.total_energy_per_unit_area_baseline,
    d.total_energy_per_unit_area_design,
    COALESCE(b.conditioned_area, d.conditioned_area) AS conditioned_area,
    COALESCE(b.company_id, d.company_id) AS company_id,
    COALESCE(b.project_phase, d.project_phase) AS project_phase,
    COALESCE(b.project_use_type, d.project_use_type) AS project_use_type,
    b.total_energy AS total_energy_baseline,
    d.total_energy AS total_energy_design,
    COALESCE(b.renewables, d.renewables) AS renewables
   FROM (baseline b
     FULL JOIN design d ON ((b.project_id = d.project_id)));


create or replace view "public"."project_latest_upload_by_type5" as  WITH ranked_uploads AS (
         SELECT p.id AS project_id,
            p.project_name AS proj_name,
            u.created_at AS upload_created_at,
            ud_1.id,
            ud_1.report_type,
            ud_1.use_type_total_area,
            ud_1.area_units,
            ud_1.energy_units,
            ud_1."Heating_Electricity",
            ud_1."Heating_NaturalGas",
            ud_1."Heating_DistrictHeating",
            ud_1."Heating_Other",
            ud_1."Cooling_Electricity",
            ud_1."Cooling_DistrictHeating",
            ud_1."Cooling_Other",
            ud_1."DHW_Electricity",
            ud_1."DHW_NaturalGas",
            ud_1."DHW_DistrictHeating",
            ud_1."DHW_Other",
            ud_1."Interior Lighting_Electricity",
            ud_1."Exterior Lighting_Electricity",
            ud_1."Plug Loads_Electricity",
            ud_1."Fans_Electricity",
            ud_1."Pumps_Electricity",
            ud_1."Pumps_NaturalGas",
            ud_1."Process Refrigeration_Electricity",
            ud_1."ExteriorUsage_Electricity",
            ud_1."ExteriorUsage_NaturalGas",
            ud_1."OtherEndUse_Electricity",
            ud_1."OtherEndUse_NaturalGas",
            ud_1."OtherEndUse_Other",
            ud_1."Heat Rejection_Electricity",
            ud_1."Humidification_Electricity",
            ud_1."HeatRecovery_Electricity",
            ud_1."HeatRecovery_Other",
            ud_1."SolarDHW_On-SiteRenewables",
            ud_1."SolarPV_On-SiteRenewables",
            ud_1."Wind_On-SiteRenewables",
            ud_1."Other_On-SiteRenewables",
            ud_1."total_Electricity",
            ud_1."total_NaturalGas",
            ud_1."total_DistrictHeating",
            ud_1."total_Other",
            ud_1."total_On-SiteRenewables",
            ud_1.total_energy,
            ud_1.project_name,
            ud_1.weather_string,
            ud_1.weather_station,
            ud_1.climate_zone,
            ud_1.file_url,
            ud_1.upload_id,
            ud_1.baseline_design,
            row_number() OVER (PARTITION BY p.id, ud_1.baseline_design ORDER BY u.created_at DESC) AS rn,
            p.company_id,
            pcc.name AS project_construction_category,
            put.name AS project_use_type,
            pp.name AS project_phase
           FROM ((((((projects p
             JOIN uploads u ON ((p.id = u.project_id)))
             JOIN eeu_data ud_1 ON ((u.id = ud_1.upload_id)))
             LEFT JOIN enum_climate_zones cz ON ((u.climate_zone_id = cz.id)))
             LEFT JOIN enum_project_construction_categories pcc ON ((u.project_construction_category_id = pcc.id)))
             LEFT JOIN enum_project_use_types put ON ((u.project_use_type_id = put.id)))
             LEFT JOIN enum_project_phases pp ON ((u.project_phase_id = pp.id)))
        )
 SELECT ranked_uploads.project_id,
    ranked_uploads.proj_name,
    ranked_uploads.upload_created_at,
    ranked_uploads.id,
    ranked_uploads.report_type,
    ranked_uploads.use_type_total_area,
    ranked_uploads.area_units,
    ranked_uploads.energy_units,
    ranked_uploads."Heating_Electricity",
    ranked_uploads."Heating_NaturalGas",
    ranked_uploads."Heating_DistrictHeating",
    ranked_uploads."Heating_Other",
    ranked_uploads."Cooling_Electricity",
    ranked_uploads."Cooling_DistrictHeating",
    ranked_uploads."Cooling_Other",
    ranked_uploads."DHW_Electricity",
    ranked_uploads."DHW_NaturalGas",
    ranked_uploads."DHW_DistrictHeating",
    ranked_uploads."DHW_Other",
    ranked_uploads."Interior Lighting_Electricity",
    ranked_uploads."Exterior Lighting_Electricity",
    ranked_uploads."Plug Loads_Electricity",
    ranked_uploads."Fans_Electricity",
    ranked_uploads."Pumps_Electricity",
    ranked_uploads."Pumps_NaturalGas",
    ranked_uploads."Process Refrigeration_Electricity",
    ranked_uploads."ExteriorUsage_Electricity",
    ranked_uploads."ExteriorUsage_NaturalGas",
    ranked_uploads."OtherEndUse_Electricity",
    ranked_uploads."OtherEndUse_NaturalGas",
    ranked_uploads."OtherEndUse_Other",
    ranked_uploads."Heat Rejection_Electricity",
    ranked_uploads."Humidification_Electricity",
    ranked_uploads."HeatRecovery_Electricity",
    ranked_uploads."HeatRecovery_Other",
    ranked_uploads."SolarDHW_On-SiteRenewables",
    ranked_uploads."SolarPV_On-SiteRenewables",
    ranked_uploads."Wind_On-SiteRenewables",
    ranked_uploads."Other_On-SiteRenewables",
    ranked_uploads."total_Electricity",
    ranked_uploads."total_NaturalGas",
    ranked_uploads."total_DistrictHeating",
    ranked_uploads."total_Other",
    ranked_uploads."total_On-SiteRenewables",
    ranked_uploads.total_energy,
    ranked_uploads.project_name,
    ranked_uploads.weather_string,
    ranked_uploads.weather_station,
    ranked_uploads.climate_zone,
    ranked_uploads.file_url,
    ranked_uploads.upload_id,
    ranked_uploads.baseline_design,
    ranked_uploads.rn,
    ranked_uploads.company_id,
    ranked_uploads.project_construction_category,
    ranked_uploads.project_use_type,
    ranked_uploads.project_phase
   FROM (ranked_uploads
     JOIN eeu_data ud ON ((ranked_uploads.id = ud.id)))
  WHERE (ranked_uploads.rn = 1);


CREATE OR REPLACE FUNCTION public.update_user_profile()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
BEGIN
  -- Update the corresponding profile in the public.profiles table
  UPDATE public.profiles
  SET email = NEW.email, 
      confirmed_at = NEW.confirmed_at, 
      last_logged_in_at = NEW.last_sign_in_at
  WHERE id = NEW.id;

  RETURN NEW;
END;
$function$
;

grant delete on table "public"."companies" to "anon";

grant insert on table "public"."companies" to "anon";

grant references on table "public"."companies" to "anon";

grant select on table "public"."companies" to "anon";

grant trigger on table "public"."companies" to "anon";

grant truncate on table "public"."companies" to "anon";

grant update on table "public"."companies" to "anon";

grant delete on table "public"."companies" to "authenticated";

grant insert on table "public"."companies" to "authenticated";

grant references on table "public"."companies" to "authenticated";

grant select on table "public"."companies" to "authenticated";

grant trigger on table "public"."companies" to "authenticated";

grant truncate on table "public"."companies" to "authenticated";

grant update on table "public"."companies" to "authenticated";

grant delete on table "public"."companies" to "service_role";

grant insert on table "public"."companies" to "service_role";

grant references on table "public"."companies" to "service_role";

grant select on table "public"."companies" to "service_role";

grant trigger on table "public"."companies" to "service_role";

grant truncate on table "public"."companies" to "service_role";

grant update on table "public"."companies" to "service_role";

grant delete on table "public"."eeu_data" to "anon";

grant insert on table "public"."eeu_data" to "anon";

grant references on table "public"."eeu_data" to "anon";

grant select on table "public"."eeu_data" to "anon";

grant trigger on table "public"."eeu_data" to "anon";

grant truncate on table "public"."eeu_data" to "anon";

grant update on table "public"."eeu_data" to "anon";

grant delete on table "public"."eeu_data" to "authenticated";

grant insert on table "public"."eeu_data" to "authenticated";

grant references on table "public"."eeu_data" to "authenticated";

grant select on table "public"."eeu_data" to "authenticated";

grant trigger on table "public"."eeu_data" to "authenticated";

grant truncate on table "public"."eeu_data" to "authenticated";

grant update on table "public"."eeu_data" to "authenticated";

grant delete on table "public"."eeu_data" to "service_role";

grant insert on table "public"."eeu_data" to "service_role";

grant references on table "public"."eeu_data" to "service_role";

grant select on table "public"."eeu_data" to "service_role";

grant trigger on table "public"."eeu_data" to "service_role";

grant truncate on table "public"."eeu_data" to "service_role";

grant update on table "public"."eeu_data" to "service_role";

grant delete on table "public"."enum_climate_zones" to "anon";

grant insert on table "public"."enum_climate_zones" to "anon";

grant references on table "public"."enum_climate_zones" to "anon";

grant select on table "public"."enum_climate_zones" to "anon";

grant trigger on table "public"."enum_climate_zones" to "anon";

grant truncate on table "public"."enum_climate_zones" to "anon";

grant update on table "public"."enum_climate_zones" to "anon";

grant delete on table "public"."enum_climate_zones" to "authenticated";

grant insert on table "public"."enum_climate_zones" to "authenticated";

grant references on table "public"."enum_climate_zones" to "authenticated";

grant select on table "public"."enum_climate_zones" to "authenticated";

grant trigger on table "public"."enum_climate_zones" to "authenticated";

grant truncate on table "public"."enum_climate_zones" to "authenticated";

grant update on table "public"."enum_climate_zones" to "authenticated";

grant delete on table "public"."enum_climate_zones" to "service_role";

grant insert on table "public"."enum_climate_zones" to "service_role";

grant references on table "public"."enum_climate_zones" to "service_role";

grant select on table "public"."enum_climate_zones" to "service_role";

grant trigger on table "public"."enum_climate_zones" to "service_role";

grant truncate on table "public"."enum_climate_zones" to "service_role";

grant update on table "public"."enum_climate_zones" to "service_role";

grant delete on table "public"."enum_energy_codes" to "anon";

grant insert on table "public"."enum_energy_codes" to "anon";

grant references on table "public"."enum_energy_codes" to "anon";

grant select on table "public"."enum_energy_codes" to "anon";

grant trigger on table "public"."enum_energy_codes" to "anon";

grant truncate on table "public"."enum_energy_codes" to "anon";

grant update on table "public"."enum_energy_codes" to "anon";

grant delete on table "public"."enum_energy_codes" to "authenticated";

grant insert on table "public"."enum_energy_codes" to "authenticated";

grant references on table "public"."enum_energy_codes" to "authenticated";

grant select on table "public"."enum_energy_codes" to "authenticated";

grant trigger on table "public"."enum_energy_codes" to "authenticated";

grant truncate on table "public"."enum_energy_codes" to "authenticated";

grant update on table "public"."enum_energy_codes" to "authenticated";

grant delete on table "public"."enum_energy_codes" to "service_role";

grant insert on table "public"."enum_energy_codes" to "service_role";

grant references on table "public"."enum_energy_codes" to "service_role";

grant select on table "public"."enum_energy_codes" to "service_role";

grant trigger on table "public"."enum_energy_codes" to "service_role";

grant truncate on table "public"."enum_energy_codes" to "service_role";

grant update on table "public"."enum_energy_codes" to "service_role";

grant delete on table "public"."enum_project_construction_categories" to "anon";

grant insert on table "public"."enum_project_construction_categories" to "anon";

grant references on table "public"."enum_project_construction_categories" to "anon";

grant select on table "public"."enum_project_construction_categories" to "anon";

grant trigger on table "public"."enum_project_construction_categories" to "anon";

grant truncate on table "public"."enum_project_construction_categories" to "anon";

grant update on table "public"."enum_project_construction_categories" to "anon";

grant delete on table "public"."enum_project_construction_categories" to "authenticated";

grant insert on table "public"."enum_project_construction_categories" to "authenticated";

grant references on table "public"."enum_project_construction_categories" to "authenticated";

grant select on table "public"."enum_project_construction_categories" to "authenticated";

grant trigger on table "public"."enum_project_construction_categories" to "authenticated";

grant truncate on table "public"."enum_project_construction_categories" to "authenticated";

grant update on table "public"."enum_project_construction_categories" to "authenticated";

grant delete on table "public"."enum_project_construction_categories" to "service_role";

grant insert on table "public"."enum_project_construction_categories" to "service_role";

grant references on table "public"."enum_project_construction_categories" to "service_role";

grant select on table "public"."enum_project_construction_categories" to "service_role";

grant trigger on table "public"."enum_project_construction_categories" to "service_role";

grant truncate on table "public"."enum_project_construction_categories" to "service_role";

grant update on table "public"."enum_project_construction_categories" to "service_role";

grant delete on table "public"."enum_project_phases" to "anon";

grant insert on table "public"."enum_project_phases" to "anon";

grant references on table "public"."enum_project_phases" to "anon";

grant select on table "public"."enum_project_phases" to "anon";

grant trigger on table "public"."enum_project_phases" to "anon";

grant truncate on table "public"."enum_project_phases" to "anon";

grant update on table "public"."enum_project_phases" to "anon";

grant delete on table "public"."enum_project_phases" to "authenticated";

grant insert on table "public"."enum_project_phases" to "authenticated";

grant references on table "public"."enum_project_phases" to "authenticated";

grant select on table "public"."enum_project_phases" to "authenticated";

grant trigger on table "public"."enum_project_phases" to "authenticated";

grant truncate on table "public"."enum_project_phases" to "authenticated";

grant update on table "public"."enum_project_phases" to "authenticated";

grant delete on table "public"."enum_project_phases" to "service_role";

grant insert on table "public"."enum_project_phases" to "service_role";

grant references on table "public"."enum_project_phases" to "service_role";

grant select on table "public"."enum_project_phases" to "service_role";

grant trigger on table "public"."enum_project_phases" to "service_role";

grant truncate on table "public"."enum_project_phases" to "service_role";

grant update on table "public"."enum_project_phases" to "service_role";

grant delete on table "public"."enum_project_use_types" to "anon";

grant insert on table "public"."enum_project_use_types" to "anon";

grant references on table "public"."enum_project_use_types" to "anon";

grant select on table "public"."enum_project_use_types" to "anon";

grant trigger on table "public"."enum_project_use_types" to "anon";

grant truncate on table "public"."enum_project_use_types" to "anon";

grant update on table "public"."enum_project_use_types" to "anon";

grant delete on table "public"."enum_project_use_types" to "authenticated";

grant insert on table "public"."enum_project_use_types" to "authenticated";

grant references on table "public"."enum_project_use_types" to "authenticated";

grant select on table "public"."enum_project_use_types" to "authenticated";

grant trigger on table "public"."enum_project_use_types" to "authenticated";

grant truncate on table "public"."enum_project_use_types" to "authenticated";

grant update on table "public"."enum_project_use_types" to "authenticated";

grant delete on table "public"."enum_project_use_types" to "service_role";

grant insert on table "public"."enum_project_use_types" to "service_role";

grant references on table "public"."enum_project_use_types" to "service_role";

grant select on table "public"."enum_project_use_types" to "service_role";

grant trigger on table "public"."enum_project_use_types" to "service_role";

grant truncate on table "public"."enum_project_use_types" to "service_role";

grant update on table "public"."enum_project_use_types" to "service_role";

grant delete on table "public"."enum_report_types" to "anon";

grant insert on table "public"."enum_report_types" to "anon";

grant references on table "public"."enum_report_types" to "anon";

grant select on table "public"."enum_report_types" to "anon";

grant trigger on table "public"."enum_report_types" to "anon";

grant truncate on table "public"."enum_report_types" to "anon";

grant update on table "public"."enum_report_types" to "anon";

grant delete on table "public"."enum_report_types" to "authenticated";

grant insert on table "public"."enum_report_types" to "authenticated";

grant references on table "public"."enum_report_types" to "authenticated";

grant select on table "public"."enum_report_types" to "authenticated";

grant trigger on table "public"."enum_report_types" to "authenticated";

grant truncate on table "public"."enum_report_types" to "authenticated";

grant update on table "public"."enum_report_types" to "authenticated";

grant delete on table "public"."enum_report_types" to "service_role";

grant insert on table "public"."enum_report_types" to "service_role";

grant references on table "public"."enum_report_types" to "service_role";

grant select on table "public"."enum_report_types" to "service_role";

grant trigger on table "public"."enum_report_types" to "service_role";

grant truncate on table "public"."enum_report_types" to "service_role";

grant update on table "public"."enum_report_types" to "service_role";

grant delete on table "public"."enum_upload_statuses" to "anon";

grant insert on table "public"."enum_upload_statuses" to "anon";

grant references on table "public"."enum_upload_statuses" to "anon";

grant select on table "public"."enum_upload_statuses" to "anon";

grant trigger on table "public"."enum_upload_statuses" to "anon";

grant truncate on table "public"."enum_upload_statuses" to "anon";

grant update on table "public"."enum_upload_statuses" to "anon";

grant delete on table "public"."enum_upload_statuses" to "authenticated";

grant insert on table "public"."enum_upload_statuses" to "authenticated";

grant references on table "public"."enum_upload_statuses" to "authenticated";

grant select on table "public"."enum_upload_statuses" to "authenticated";

grant trigger on table "public"."enum_upload_statuses" to "authenticated";

grant truncate on table "public"."enum_upload_statuses" to "authenticated";

grant update on table "public"."enum_upload_statuses" to "authenticated";

grant delete on table "public"."enum_upload_statuses" to "service_role";

grant insert on table "public"."enum_upload_statuses" to "service_role";

grant references on table "public"."enum_upload_statuses" to "service_role";

grant select on table "public"."enum_upload_statuses" to "service_role";

grant trigger on table "public"."enum_upload_statuses" to "service_role";

grant truncate on table "public"."enum_upload_statuses" to "service_role";

grant update on table "public"."enum_upload_statuses" to "service_role";

grant delete on table "public"."profiles" to "service_role";

grant insert on table "public"."profiles" to "service_role";

grant references on table "public"."profiles" to "service_role";

grant select on table "public"."profiles" to "service_role";

grant trigger on table "public"."profiles" to "service_role";

grant truncate on table "public"."profiles" to "service_role";

grant update on table "public"."profiles" to "service_role";

grant delete on table "public"."profiles" to "supabase_auth_admin";

grant insert on table "public"."profiles" to "supabase_auth_admin";

grant references on table "public"."profiles" to "supabase_auth_admin";

grant select on table "public"."profiles" to "supabase_auth_admin";

grant trigger on table "public"."profiles" to "supabase_auth_admin";

grant truncate on table "public"."profiles" to "supabase_auth_admin";

grant update on table "public"."profiles" to "supabase_auth_admin";

grant delete on table "public"."projects" to "anon";

grant insert on table "public"."projects" to "anon";

grant references on table "public"."projects" to "anon";

grant select on table "public"."projects" to "anon";

grant trigger on table "public"."projects" to "anon";

grant truncate on table "public"."projects" to "anon";

grant update on table "public"."projects" to "anon";

grant delete on table "public"."projects" to "authenticated";

grant insert on table "public"."projects" to "authenticated";

grant references on table "public"."projects" to "authenticated";

grant select on table "public"."projects" to "authenticated";

grant trigger on table "public"."projects" to "authenticated";

grant truncate on table "public"."projects" to "authenticated";

grant update on table "public"."projects" to "authenticated";

grant delete on table "public"."projects" to "service_role";

grant insert on table "public"."projects" to "service_role";

grant references on table "public"."projects" to "service_role";

grant select on table "public"."projects" to "service_role";

grant trigger on table "public"."projects" to "service_role";

grant truncate on table "public"."projects" to "service_role";

grant update on table "public"."projects" to "service_role";

grant delete on table "public"."uploads" to "anon";

grant insert on table "public"."uploads" to "anon";

grant references on table "public"."uploads" to "anon";

grant select on table "public"."uploads" to "anon";

grant trigger on table "public"."uploads" to "anon";

grant truncate on table "public"."uploads" to "anon";

grant update on table "public"."uploads" to "anon";

grant delete on table "public"."uploads" to "authenticated";

grant insert on table "public"."uploads" to "authenticated";

grant references on table "public"."uploads" to "authenticated";

grant select on table "public"."uploads" to "authenticated";

grant trigger on table "public"."uploads" to "authenticated";

grant truncate on table "public"."uploads" to "authenticated";

grant update on table "public"."uploads" to "authenticated";

grant delete on table "public"."uploads" to "service_role";

grant insert on table "public"."uploads" to "service_role";

grant references on table "public"."uploads" to "service_role";

grant select on table "public"."uploads" to "service_role";

grant trigger on table "public"."uploads" to "service_role";

grant truncate on table "public"."uploads" to "service_role";

grant update on table "public"."uploads" to "service_role";

grant delete on table "public"."users" to "anon";

grant insert on table "public"."users" to "anon";

grant references on table "public"."users" to "anon";

grant select on table "public"."users" to "anon";

grant trigger on table "public"."users" to "anon";

grant truncate on table "public"."users" to "anon";

grant update on table "public"."users" to "anon";

grant delete on table "public"."users" to "authenticated";

grant insert on table "public"."users" to "authenticated";

grant references on table "public"."users" to "authenticated";

grant select on table "public"."users" to "authenticated";

grant trigger on table "public"."users" to "authenticated";

grant truncate on table "public"."users" to "authenticated";

grant update on table "public"."users" to "authenticated";

grant delete on table "public"."users" to "service_role";

grant insert on table "public"."users" to "service_role";

grant references on table "public"."users" to "service_role";

grant select on table "public"."users" to "service_role";

grant trigger on table "public"."users" to "service_role";

grant truncate on table "public"."users" to "service_role";

grant update on table "public"."users" to "service_role";

create policy "Enable insert for authenticated users only"
on "public"."companies"
as permissive
for all
to authenticated
with check (true);


create policy "select_only_authenticated"
on "public"."companies"
as permissive
for select
to public
using ((auth.uid() IS NOT NULL));


create policy "select_for_authenticated_users"
on "public"."eeu_data"
as permissive
for select
to public
using ((auth.uid() IS NOT NULL));


create policy "select authenticated only"
on "public"."enum_climate_zones"
as permissive
for select
to public
using ((auth.uid() IS NOT NULL));


create policy "auth req for all"
on "public"."enum_energy_codes"
as permissive
for all
to public
using ((auth.uid() IS NOT NULL))
with check ((auth.uid() IS NOT NULL));


create policy "req for all"
on "public"."enum_project_construction_categories"
as permissive
for all
to public
using ((auth.uid() IS NOT NULL))
with check ((auth.uid() IS NOT NULL));


create policy "req for all"
on "public"."enum_project_phases"
as permissive
for all
to public
using ((auth.uid() IS NOT NULL))
with check ((auth.uid() IS NOT NULL));


create policy "auth req for all"
on "public"."enum_project_use_types"
as permissive
for all
to public
using ((auth.uid() IS NOT NULL))
with check ((auth.uid() IS NOT NULL));


create policy "auth req for all"
on "public"."enum_report_types"
as permissive
for all
to public
using ((auth.uid() IS NOT NULL))
with check ((auth.uid() IS NOT NULL));


create policy "auth req for all"
on "public"."enum_upload_statuses"
as permissive
for all
to public
using ((auth.uid() IS NOT NULL))
with check ((auth.uid() IS NOT NULL));


create policy "Allow authenticated users to update data."
on "public"."profiles"
as permissive
for update
to public
using (((auth.uid())::text = CURRENT_USER));


create policy "Public profiles are viewable by everyone."
on "public"."profiles"
as permissive
for select
to public
using (true);


create policy "Users can insert their own profile."
on "public"."profiles"
as permissive
for insert
to public
with check ((auth.uid() = id));


create policy "select auth only"
on "public"."profiles"
as permissive
for all
to public
using ((auth.uid() IS NOT NULL))
with check ((auth.uid() IS NOT NULL));


create policy "Enable insert for authenticated users only"
on "public"."projects"
as permissive
for insert
to authenticated
with check (true);


create policy "select_only_authenticated"
on "public"."projects"
as permissive
for select
to public
using ((auth.uid() IS NOT NULL));


create policy "Enable insert for authenticated users only"
on "public"."uploads"
as permissive
for insert
to authenticated
with check (true);


create policy "Enable insert for users based on user_id"
on "public"."uploads"
as permissive
for insert
to public
with check (true);



