create type "public"."fuel_types" as enum ('electricity', 'fossil_fuels', 'district', 'other');

create table "public"."upload_batches" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "user_id" uuid
);


alter table "public"."upload_batches" enable row level security;

alter table "public"."eeu_data" add column "upload_batch_id" integer;

alter table "public"."eeu_fields" drop column "display_name";

alter table "public"."eeu_fields" drop column "energy_type";

alter table "public"."eeu_fields" add column "fuel_category" fuel_types;

alter table "public"."eeu_fields" add column "fuel_type" text;

alter table "public"."eeu_fields" add column "id" bigint generated by default as identity not null;

alter table "public"."eeu_fields" add column "use_type" text;

alter table "public"."uploads" add column "upload_batch_id" integer;

CREATE UNIQUE INDEX eeu_fields_id_key ON public.eeu_fields USING btree (id);

CREATE UNIQUE INDEX eeu_fields_pkey ON public.eeu_fields USING btree (id);

CREATE UNIQUE INDEX upload_batches_pkey ON public.upload_batches USING btree (id);

alter table "public"."eeu_fields" add constraint "eeu_fields_pkey" PRIMARY KEY using index "eeu_fields_pkey";

alter table "public"."upload_batches" add constraint "upload_batches_pkey" PRIMARY KEY using index "upload_batches_pkey";

alter table "public"."eeu_fields" add constraint "eeu_fields_id_key" UNIQUE using index "eeu_fields_id_key";

grant delete on table "public"."upload_batches" to "anon";

grant insert on table "public"."upload_batches" to "anon";

grant references on table "public"."upload_batches" to "anon";

grant select on table "public"."upload_batches" to "anon";

grant trigger on table "public"."upload_batches" to "anon";

grant truncate on table "public"."upload_batches" to "anon";

grant update on table "public"."upload_batches" to "anon";

grant delete on table "public"."upload_batches" to "authenticated";

grant insert on table "public"."upload_batches" to "authenticated";

grant references on table "public"."upload_batches" to "authenticated";

grant select on table "public"."upload_batches" to "authenticated";

grant trigger on table "public"."upload_batches" to "authenticated";

grant truncate on table "public"."upload_batches" to "authenticated";

grant update on table "public"."upload_batches" to "authenticated";

grant delete on table "public"."upload_batches" to "service_role";

grant insert on table "public"."upload_batches" to "service_role";

grant references on table "public"."upload_batches" to "service_role";

grant select on table "public"."upload_batches" to "service_role";

grant trigger on table "public"."upload_batches" to "service_role";

grant truncate on table "public"."upload_batches" to "service_role";

grant update on table "public"."upload_batches" to "service_role";


