create table "public"."integrations_sync" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "project_id" text,
    "response" text,
    "response_code" text,
    "external_id" text
);


alter table "public"."integrations_sync" enable row level security;

alter table "public"."companies" add column "ddx_firm_key" text;

alter table "public"."eeu_data" add column "city" text;

alter table "public"."eeu_data" add column "state" text;

alter table "public"."projects" add column "ddx_upload_id" integer;

CREATE UNIQUE INDEX ddx_api_calls_pkey ON public.integrations_sync USING btree (id);

alter table "public"."integrations_sync" add constraint "ddx_api_calls_pkey" PRIMARY KEY using index "ddx_api_calls_pkey";

grant delete on table "public"."integrations_sync" to "anon";

grant insert on table "public"."integrations_sync" to "anon";

grant references on table "public"."integrations_sync" to "anon";

grant select on table "public"."integrations_sync" to "anon";

grant trigger on table "public"."integrations_sync" to "anon";

grant truncate on table "public"."integrations_sync" to "anon";

grant update on table "public"."integrations_sync" to "anon";

grant delete on table "public"."integrations_sync" to "authenticated";

grant insert on table "public"."integrations_sync" to "authenticated";

grant references on table "public"."integrations_sync" to "authenticated";

grant select on table "public"."integrations_sync" to "authenticated";

grant trigger on table "public"."integrations_sync" to "authenticated";

grant truncate on table "public"."integrations_sync" to "authenticated";

grant update on table "public"."integrations_sync" to "authenticated";

grant delete on table "public"."integrations_sync" to "service_role";

grant insert on table "public"."integrations_sync" to "service_role";

grant references on table "public"."integrations_sync" to "service_role";

grant select on table "public"."integrations_sync" to "service_role";

grant trigger on table "public"."integrations_sync" to "service_role";

grant truncate on table "public"."integrations_sync" to "service_role";

grant update on table "public"."integrations_sync" to "service_role";


