create table "public"."data_viz_chart_options" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "visualization_name" text,
    "y_axis_field" text,
    "x_axis_field" text
);


alter table "public"."data_viz_chart_options" enable row level security;

CREATE UNIQUE INDEX data_viz_chart_eeu_options_id_key ON public.data_viz_chart_options USING btree (id);

CREATE UNIQUE INDEX data_viz_chart_eeu_options_pkey ON public.data_viz_chart_options USING btree (id);

CREATE UNIQUE INDEX eeu_fields_field_name_key ON public.eeu_fields USING btree (field_name);

alter table "public"."data_viz_chart_options" add constraint "data_viz_chart_eeu_options_pkey" PRIMARY KEY using index "data_viz_chart_eeu_options_pkey";

alter table "public"."data_viz_chart_options" add constraint "data_viz_chart_eeu_options_id_key" UNIQUE using index "data_viz_chart_eeu_options_id_key";

alter table "public"."eeu_fields" add constraint "eeu_fields_field_name_key" UNIQUE using index "eeu_fields_field_name_key";

grant delete on table "public"."data_viz_chart_options" to "anon";

grant insert on table "public"."data_viz_chart_options" to "anon";

grant references on table "public"."data_viz_chart_options" to "anon";

grant select on table "public"."data_viz_chart_options" to "anon";

grant trigger on table "public"."data_viz_chart_options" to "anon";

grant truncate on table "public"."data_viz_chart_options" to "anon";

grant update on table "public"."data_viz_chart_options" to "anon";

grant delete on table "public"."data_viz_chart_options" to "authenticated";

grant insert on table "public"."data_viz_chart_options" to "authenticated";

grant references on table "public"."data_viz_chart_options" to "authenticated";

grant select on table "public"."data_viz_chart_options" to "authenticated";

grant trigger on table "public"."data_viz_chart_options" to "authenticated";

grant truncate on table "public"."data_viz_chart_options" to "authenticated";

grant update on table "public"."data_viz_chart_options" to "authenticated";

grant delete on table "public"."data_viz_chart_options" to "service_role";

grant insert on table "public"."data_viz_chart_options" to "service_role";

grant references on table "public"."data_viz_chart_options" to "service_role";

grant select on table "public"."data_viz_chart_options" to "service_role";

grant trigger on table "public"."data_viz_chart_options" to "service_role";

grant truncate on table "public"."data_viz_chart_options" to "service_role";

grant update on table "public"."data_viz_chart_options" to "service_role";


