create table "public"."ddx_keys" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "user_id" uuid default gen_random_uuid(),
    "user_key" text,
    "firm_key" text
);


alter table "public"."ddx_keys" enable row level security;

alter table "public"."enum_energy_codes" add column "included_ddx" boolean;

CREATE UNIQUE INDEX ddx_keys_pkey ON public.ddx_keys USING btree (id);

alter table "public"."ddx_keys" add constraint "ddx_keys_pkey" PRIMARY KEY using index "ddx_keys_pkey";

grant delete on table "public"."ddx_keys" to "anon";

grant insert on table "public"."ddx_keys" to "anon";

grant references on table "public"."ddx_keys" to "anon";

grant select on table "public"."ddx_keys" to "anon";

grant trigger on table "public"."ddx_keys" to "anon";

grant truncate on table "public"."ddx_keys" to "anon";

grant update on table "public"."ddx_keys" to "anon";

grant delete on table "public"."ddx_keys" to "authenticated";

grant insert on table "public"."ddx_keys" to "authenticated";

grant references on table "public"."ddx_keys" to "authenticated";

grant select on table "public"."ddx_keys" to "authenticated";

grant trigger on table "public"."ddx_keys" to "authenticated";

grant truncate on table "public"."ddx_keys" to "authenticated";

grant update on table "public"."ddx_keys" to "authenticated";

grant delete on table "public"."ddx_keys" to "service_role";

grant insert on table "public"."ddx_keys" to "service_role";

grant references on table "public"."ddx_keys" to "service_role";

grant select on table "public"."ddx_keys" to "service_role";

grant trigger on table "public"."ddx_keys" to "service_role";

grant truncate on table "public"."ddx_keys" to "service_role";

grant update on table "public"."ddx_keys" to "service_role";


