create table "public"."ddx_energy_codes" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "ddx_energy_code" text
);


alter table "public"."ddx_energy_codes" enable row level security;

alter table "public"."enum_energy_codes" add column "ddx_energy_code_id" bigint;

CREATE UNIQUE INDEX ddx_energy_codes_pkey ON public.ddx_energy_codes USING btree (id);

alter table "public"."ddx_energy_codes" add constraint "ddx_energy_codes_pkey" PRIMARY KEY using index "ddx_energy_codes_pkey";

alter table "public"."enum_energy_codes" add constraint "enum_energy_codes_ddx_energy_code_id_fkey" FOREIGN KEY (ddx_energy_code_id) REFERENCES ddx_energy_codes(id) not valid;

alter table "public"."enum_energy_codes" validate constraint "enum_energy_codes_ddx_energy_code_id_fkey";

grant delete on table "public"."ddx_energy_codes" to "anon";

grant insert on table "public"."ddx_energy_codes" to "anon";

grant references on table "public"."ddx_energy_codes" to "anon";

grant select on table "public"."ddx_energy_codes" to "anon";

grant trigger on table "public"."ddx_energy_codes" to "anon";

grant truncate on table "public"."ddx_energy_codes" to "anon";

grant update on table "public"."ddx_energy_codes" to "anon";

grant delete on table "public"."ddx_energy_codes" to "authenticated";

grant insert on table "public"."ddx_energy_codes" to "authenticated";

grant references on table "public"."ddx_energy_codes" to "authenticated";

grant select on table "public"."ddx_energy_codes" to "authenticated";

grant trigger on table "public"."ddx_energy_codes" to "authenticated";

grant truncate on table "public"."ddx_energy_codes" to "authenticated";

grant update on table "public"."ddx_energy_codes" to "authenticated";

grant delete on table "public"."ddx_energy_codes" to "service_role";

grant insert on table "public"."ddx_energy_codes" to "service_role";

grant references on table "public"."ddx_energy_codes" to "service_role";

grant select on table "public"."ddx_energy_codes" to "service_role";

grant trigger on table "public"."ddx_energy_codes" to "service_role";

grant truncate on table "public"."ddx_energy_codes" to "service_role";

grant update on table "public"."ddx_energy_codes" to "service_role";


